### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by viljoviitanen** [judofyr/perloku#12]
Hello,

Could you please include a license, or even a mention of how the buildback is licensed? (e.g. "same as perl 5")

**Comment by judofyr** [comment]
MIT. I'll add a license later.

On Wednesday, August 20, 2014, Viljo Viitanen notifications@github.com
wrote:

> Hello,
> 
> Could you please include a license, or even a mention of how the buildback
> is licensed? (e.g. "same as perl 5")
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/judofyr/perloku/issues/12.

## 

// Magnus Holm

**Comment by viljoviitanen** [comment]
Great, thanks!

**Comment by judofyr** [comment]
Added in f5a55a8cb441eaaaa5216d8aa0bd32927a557fc8.
