### ISSUE TITLE
Use recent perl version

### ISSUE THREAD

**Issue by memowe** [judofyr/perloku#15]
Hey @judofyr, thank you so much for your work!

Please use a more recent perl version than the hard-coded 5.18.1 from your AWS, at least 5.20+. Is there maybe a better way than using the tarball from AWS nowadays?

Thank you, best wishes

**Comment by judofyr** [comment]
I don't know what's the recommended way to build custom buildpacks these days. I'm guessing it's based on Dockerfile. I'm not using this for anything so I don't have any big plans in making an updated one unfortunately.

**Comment by memowe** [comment]
OK, thanks anyway!
