### ISSUE TITLE
Module Dancer::Plugin::Mongo crashes when deployed

### ISSUE THREAD

**Issue by gatlin** [judofyr/perloku#4]
Following your instructions, I have an app that uses Dancer::Plugin::Mongo which works (ie, writes to MongoHQ) on my machine but when deployed, `heroku logs` says that the app crashes right after loading Dancer::Plugin::Mongo. It builds, and all the dependencies are built, but there must be something different about the deployment architecture that I'm not aware of. I obviously don't expect you to magically know my app or this third-party module but do you have any hunches? I need to read more about Heroku.

However, solid buildpack. I will be using this for other projects.

**Comment by judofyr** [comment]
The Perl installation is compiled in a different directory than it's located on the Dyno, so it might look for dependencies/stuff in an non-existent directory. Try running `heroku run bash` and see if you can get a better stack trace (`perl -MDancer::Plugin::Mongo`).

**Comment by gatlin** [comment]
As it turns out, none of the modules specified in the makefile seem to have built. I believe I created my Makefile.PL correctly and yet none of the modules I list in it are actually built on commit.

In the heroku shell this happens as well:

```
~ $ cpanm Dancer  
bash: /app/vendor/perl/bin/cpanm: /tmp/perl/perls/perl-5.14.2/bin/perl: bad interpreter: No such file or directory
```

Same goes for the `cpan` binary.

**Comment by judofyr** [comment]
You need to use `perl -S cpanm` because the binaries created by Perl assumes that the Perl is located in /tmp/perl/perls/perl-5.14.2/bin. However, the correct environment variables should be set (PERL5LIB) so running plain `perl` should work correctly.

**Comment by gatlin** [comment]
```
~ $ perl -S cpanm Dancer
Dancer is up to date. (1.3092)
~ $ perl -MDancer
Can't locate Dancer.pm in @INC (@INC contains: /app/vendor/perl/lib/site_perl/5.14.2/x86_64-linux     /app/vendor/perl/lib/site_perl/5.14.2 /app/vendor/perl/lib/5.14.2/x86_64-linux /app/vendor/perl/lib/5.14.2 .).
BEGIN failed--compilation aborted.
```

This is what I just ran in bash. Hopefully this provides useful information.

**Comment by judofyr** [comment]
Sorry for not following this up. I'm not quite sure what version (of Perloku) you ran this on, but it seems that /app/vendor/perl-deps are missing from @INC.

I'm closing this for now; Re-open it if it's still a problem.
